waldirio/sos_analyze

- internals_help/executed_commands.txt
- internals_help/parse.sh
- sos_analyze.sh
> Log format

- internals_help/executed_commands.txt
- sos_analyze.sh
Virt-who machine based on httpd logs.
> 13 virt who sender

- sos_analyze.sh
> pulp.agent count fixed

- sos_analyze.sh
Now, it's possible to see the memory amount used at that moment.
Issue #20
> Fix: #20, memory utilization sumary

- sos_analyze.sh
Added virt-who current status.
> Fix #24, added virt-who service current status

- sos_analyze.sh
Great report that will help during the troubleshooting.
> Fix #27, added a new task report that will help during the Trouble.

- sos_analyze.sh
Tested on both logs (old sosreport and new one).
Both working as expected.
> new sosreport supportability

- internals_help/executed_commands.txt
- internals_help/parse.sh
Parse updated to show all the commands executed on the script.
> parse updated

- internals_help/executed_commands.txt
- sos_analyze.sh
Checking for katello-agent and goferd on Sat Server
> checking for goferd and katello-agent on Satellite server #35

- internals_help/executed_commands.txt
- sos_analyze.sh
Checking duplicated hypervisors
> checking duplicated hypervisors - Fix#51

- internals_help/executed_commands.txt
- sos_analyze.sh
Error info during satellite-installer / log files
> Error info during satellite-installer / log files (#49)

- internals_help/executed_commands.txt
- sos_analyze.sh
setroubleshoot package check - #58
> setroubleshoot package check

- internals_help/executed_commands.txt
- sos_analyze.sh
Checking if the machine is baremetal or vm based on issue #57
> [FEATURE] Checking if the machine is baremetal or vm

- internals_help/executed_commands.txt
- sos_analyze.sh
[FEATURE] dynflow executors added according to #63
> [FEATURE] dynflow executors added

- internals_help/executed_commands.txt
- sos_analyze.sh
[FIX] Fixed typo on dynflowd conf file/tuning query
> [FIX] Fixed typo on dynflowd conf file/tuning query

- sos_analyze.sh
> [FIX] Tuning dynflowd - fixed typo

- internals_help/executed_commands.txt
- sos_analyze.sh
presenting all the flags used with satellite-installer
> [FEATURE] presenting all the flags used with satellite-installer

- internals_help/executed_commands.txt
- sos_analyze.sh
> [FIX] Multiple qpid file path

- internals_help/executed_commands.txt
- sos_analyze.sh
Improving the visualization of hypervisors tasks.
> [ENHANCE] hypervisors task presentation

- build_changelog.sh
- changelog.log
- Changelog using the PR subject to organize and generate the list.
> [FEATURE] - Adding changelog feature

- internals_help/executed_commands.txt
- sos_analyze.sh
Getting hostname from sosreport.
> [ENHANCEMENT] - Getting hostname from sosreport.

- internals_help/executed_commands.txt
- sos_analyze.sh
Calling insights run on the fly
> insights call

- internals_help/executed_commands.txt
- sos_analyze.sh
> check the foreman tasks cleanup script

- internals_help/executed_commands.txt
- sos_analyze.sh
> puppet server test

- internals_help/executed_commands.txt
- sos_analyze.sh
> Insert qpidd information

- internals_help/executed_commands.txt
- sos_analyze.sh
> [FIX] Fixing the top 20 consumers

- sos_analyze.sh
> Capturing exit code for Last flag used with satellite-installer

- sos_analyze.sh
Replaced `grep` with the much faster `rg` at all places.
Ideally, this would happen automatically depending on `ripgrep` being installed. Feel free to block this PR until this is automated. :-)
> Fixes #109: Switch to ripgrep
